apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helm-charts
spec:
  description: Proyecto para instalar chats de aplicaciones transversales
  sourceRepos:
  - '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

 