// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

export class Keycloak extends pulumi.CustomResource {
    /**
     * Get an existing Keycloak resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Keycloak {
        return new Keycloak(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:k8s.keycloak.org/v2alpha1:Keycloak';

    /**
     * Returns true if the given object is an instance of Keycloak.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Keycloak {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Keycloak.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"k8s.keycloak.org/v2alpha1" | undefined>;
    public readonly kind!: pulumi.Output<"Keycloak" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    public readonly spec!: pulumi.Output<outputs.k8s.v2alpha1.KeycloakSpec | undefined>;
    public readonly status!: pulumi.Output<outputs.k8s.v2alpha1.KeycloakStatus | undefined>;

    /**
     * Create a Keycloak resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: KeycloakArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "k8s.keycloak.org/v2alpha1";
            resourceInputs["kind"] = "Keycloak";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Keycloak.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Keycloak resource.
 */
export interface KeycloakArgs {
    apiVersion?: pulumi.Input<"k8s.keycloak.org/v2alpha1">;
    kind?: pulumi.Input<"Keycloak">;
    metadata?: pulumi.Input<ObjectMeta>;
    spec?: pulumi.Input<inputs.k8s.v2alpha1.KeycloakSpecArgs>;
    status?: pulumi.Input<inputs.k8s.v2alpha1.KeycloakStatusArgs>;
}
