apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: default
spec:
  project: helm-charts
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.0.0
    chart: redis
    helm:
      values: |
        cluster:
          enabled: false
        replica:
          replicaCount: 0
        master:
          persistence:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true