apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: default
spec:
  project: helm-charts
  source:
    chart: openebs
    repoURL: https://openebs.github.io/charts
    helm:
      releaseName: openebs
      valueFiles:
          - openebs-values-develop.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true