---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: default
spec:
  project: az-devops-gitops
  source:
    repoURL: https://github.com/gabomgp4/bg-argocd
    path: ./argocd/echo-server/
    targetRevision: main
    helm:
      valueFiles:
        - values-develop.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: echoserver
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
