// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * define a set of Kubernetes resources (StatefulSet, PVC, Service, ConfigMap) which describe behavior one or more ClickHouse clusters
 */
export class ClickHouseInstallationTemplate extends pulumi.CustomResource {
    /**
     * Get an existing ClickHouseInstallationTemplate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ClickHouseInstallationTemplate {
        return new ClickHouseInstallationTemplate(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallationTemplate';

    /**
     * Returns true if the given object is an instance of ClickHouseInstallationTemplate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClickHouseInstallationTemplate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClickHouseInstallationTemplate.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"clickhouse.altinity.com/v1" | undefined>;
    public readonly kind!: pulumi.Output<"ClickHouseInstallationTemplate" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Specification of the desired behavior of one or more ClickHouse clusters
     * More info: https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md
     */
    public readonly spec!: pulumi.Output<outputs.clickhouse.v1.ClickHouseInstallationTemplateSpec>;
    /**
     * Current ClickHouseInstallation manifest status, contains many fields like a normalized configuration, clickhouse-operator version, current action and all applied action list, current taskID and all applied taskIDs and other
     */
    public readonly status!: pulumi.Output<outputs.clickhouse.v1.ClickHouseInstallationTemplateStatus | undefined>;

    /**
     * Create a ClickHouseInstallationTemplate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ClickHouseInstallationTemplateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "clickhouse.altinity.com/v1";
            resourceInputs["kind"] = "ClickHouseInstallationTemplate";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClickHouseInstallationTemplate.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ClickHouseInstallationTemplate resource.
 */
export interface ClickHouseInstallationTemplateArgs {
    apiVersion?: pulumi.Input<"clickhouse.altinity.com/v1">;
    kind?: pulumi.Input<"ClickHouseInstallationTemplate">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Specification of the desired behavior of one or more ClickHouse clusters
     * More info: https://github.com/Altinity/clickhouse-operator/blob/master/docs/custom_resource_explained.md
     */
    spec?: pulumi.Input<inputs.clickhouse.v1.ClickHouseInstallationTemplateSpecArgs>;
    /**
     * Current ClickHouseInstallation manifest status, contains many fields like a normalized configuration, clickhouse-operator version, current action and all applied action list, current taskID and all applied taskIDs and other
     */
    status?: pulumi.Input<inputs.clickhouse.v1.ClickHouseInstallationTemplateStatusArgs>;
}
