// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { ClickHouseInstallationArgs } from "./clickHouseInstallation";
export type ClickHouseInstallation = import("./clickHouseInstallation").ClickHouseInstallation;
export const ClickHouseInstallation: typeof import("./clickHouseInstallation").ClickHouseInstallation = null as any;
utilities.lazyLoad(exports, ["ClickHouseInstallation"], () => require("./clickHouseInstallation"));

export { ClickHouseInstallationTemplateArgs } from "./clickHouseInstallationTemplate";
export type ClickHouseInstallationTemplate = import("./clickHouseInstallationTemplate").ClickHouseInstallationTemplate;
export const ClickHouseInstallationTemplate: typeof import("./clickHouseInstallationTemplate").ClickHouseInstallationTemplate = null as any;
utilities.lazyLoad(exports, ["ClickHouseInstallationTemplate"], () => require("./clickHouseInstallationTemplate"));

export { ClickHouseOperatorConfigurationArgs } from "./clickHouseOperatorConfiguration";
export type ClickHouseOperatorConfiguration = import("./clickHouseOperatorConfiguration").ClickHouseOperatorConfiguration;
export const ClickHouseOperatorConfiguration: typeof import("./clickHouseOperatorConfiguration").ClickHouseOperatorConfiguration = null as any;
utilities.lazyLoad(exports, ["ClickHouseOperatorConfiguration"], () => require("./clickHouseOperatorConfiguration"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallation":
                return new ClickHouseInstallation(name, <any>undefined, { urn })
            case "kubernetes:clickhouse.altinity.com/v1:ClickHouseInstallationTemplate":
                return new ClickHouseInstallationTemplate(name, <any>undefined, { urn })
            case "kubernetes:clickhouse.altinity.com/v1:ClickHouseOperatorConfiguration":
                return new ClickHouseOperatorConfiguration(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("crds", "clickhouse.altinity.com/v1", _module)
