---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: default
spec:
  project: az-devops-gitops
  source:
    repoURL: https://github.com/gabomgp4/bg-argocd
    path: ./argocd/keycloak/
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
