apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: default
spec:
  project: helm-charts
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.10.9
    chart: minio
    helm:
      releaseName: bg
      parameters:
        - name: "persistence.enabled"
          value: "true"
        - name: "persistence.size"
          value: "100Gi"
        - name: "auth.rootUser"
          value: "admin"
        - name: "auth.rootPassword"
          value: "55lzpkoc0uk0k6d3"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true