apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: default
spec:
  project: helm-charts
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.10.9
    chart: minio
    helm:
      values: |
        persistence:
          enabled: true
          size: 100Gi
        auth:
          rootUser:minio-admin
          rootPassword:minio-admin
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true