apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: oidc
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    global: "false"
config:
  client_id: "kong-oidc"
  client_secret: "utFhJr77nnsMCJc4p8DhulXJIs9BnHTJ"
  realm: "kong"
  discovery: "https://{{ .Values.ingress.domain }}/keycloak/realms/kong/.well-known/openid-configuration"
  scope: "openid"
  redirect_after_logout_uri: "https://{{ .Values.ingress.domain }}/keycloak/realms/kong/protocol/openid-connect/logout?redirect_uri=https://{{ .Values.ingress.domain }}/keycloak/"
  ssl_verify: "yes"
plugin: oidc
disabled: false
---
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: https-port-plugin
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    global: "false"
config:
  access:
    - "ngx.var.upstream_x_forwarded_port=443"
plugin: post-function
disabled: false