apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: {{ .Values.postgres.instances }}
  backup:
    barmanObjectStore:
      destinationPath: "s3://bg-minio.minio.svc.homelab.local:9000/backups/keycloak-db/"
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
  storage:
    size: {{ .Values.keycloak.db.size }}
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-keycloak-db
  namespace: keycloak
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: pg-backup
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
  namespace: keycloak
spec:
  method: barmanObjectStore
  cluster:
    name: keycloak-db
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
  namespace: keycloak
type: Opaque
data:
  ACCESS_KEY_ID: NUdUd2EzRmRwTHdJU3hVNlk2aWs=
  ACCESS_SECRET_KEY: WTVkWDZveGh4SnFVd2hSVjdJR0VyTDlEWW1PVmYxV084cmRMNnRkYw==