apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: keycloak
spec:
  instances: {{ .Values.postgres.instances }}
  storage:
    size: {{ .Values.keycloak.db.size }}
