apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: default
spec:
  project: helm-charts
  source:
    chart: signoz
    repoURL: https://charts.signoz.io
    targetRevision: 0.30.4
    helm:
      releaseName: signoz
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-bg
  namespace: default
spec:
  project: helm-charts
  source:
    repoURL: https://github.com/gabomgp4/bg-argocd
    path: ./argocd/signoz/
    targetRevision: main
    helm:
      valueFiles:
        - values-develop.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
